### ISSUE TITLE
Add `monospace` as fallback for `"Fira Code"`

### ISSUE THREAD

**Issue by rben01** [LeonWong0609/logseq-default-dark-0-saturation#1]
If `"Fira Code"` is unavailable on the user's system, the presence of the `font-family` rule causes code to fall back to the default serif font. The `monospace` font should be added after, e.g., `font-family: "Fira Code", monospace;`, in order to fall back to the system monospace font.

**Comment by rben01** [comment]
Here is a screenshot of the issue: 
<img width="117" alt="image" src="https://user-images.githubusercontent.com/766670/163527473-1abc8a8f-6811-46d9-8093-bb1c84ab9fa7.png">

**Comment by l3ony2k** [comment]
Thanks, that’s a good point. I’ll fix this ASAP.

**Comment by l3ony2k** [comment]
Please check update and refresh. It should be fixed RN.

Thanks again for the issue.
